<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
		'SimpleAddressBook\Module' => __DIR__ . '/Module.php',
		'SimpleAddressBook\Controller\AbstractAuthActionController' => __DIR__ . '/src/SimpleAddressBook/Controller/AbstractAuthActionController.php',
		'SimpleAddressBook\Controller\ContactController' => __DIR__ . '/src/SimpleAddressBook/Controller/ContactController.php',
		'SimpleAddressBook\Form\ContactForm' => __DIR__ . '/src/SimpleAddressBook/Form/ContactForm.php',
		'SimpleAddressBook\Model\Contact' => __DIR__ . '/src/SimpleAddressBook/Model/Contact.php',
		'SimpleAddressBook\Model\ContactTableGateway' => __DIR__ . '/src/SimpleAddressBook/Model/ContactTableGateway.php',
		'SimpleAddressBook\Model\User' => __DIR__ . '/src/SimpleAddressBook/Model/User.php',
		'SimpleAddressBookTest\Framework\TestCase'  => __DIR__ . '/tests/SimpleAddressBookTest/Framework/TestCase.php',
);