<?php 
	$title = 'Contact List';
	$this->form->setAttribute('action', 'simple-address-book/contact/search');
	$this->form->prepare();
?>
<?= $this->headTitle($title) ?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
	<button onclick="location.href='/simple-address-book/contact/add'">Add new</button>
</p>
<div>
	<?= $this->form()->openTag($this->form) ?>
		<div><?= $this->formRow($this->form->get('q')) ?></div>
	<?= $this->form()->closeTag($this->form) ?>		
</div>
<table>
	<tr>
		<th>First name</th>
		<th>Last name</th>
		<th>Email</th>
		<th>Phone</th>
		<th>2nd Phone</th>
		<th>Street Address</th>
		<th>City</th>
		<th>State</th>
		<th>Zip</th>
		<th>Web Address</th>
		<th></th>
	</tr>
	<?php foreach($contact_list as $item) : ?>
	<tr>
		<td><?= $this->escapeHtml($item->first_name) ?></td>
		<td><?= $this->escapeHtml($item->last_name) ?></td>
		<td><a href="mailto:<?= $item->email ?>"><?= $this->escapeHtml($item->email) ?>
		</a></td>
		<td><?= $this->escapeHtml($item->phone) ?></td>
		<td><?= $item->second_phone ? $this->escapeHtml($item->second_phone) : 'None' ?>
		</td>
		<td><?= $item->street_addr ? $this->escapeHtml($item->street_addr) : 'None' ?>
		</td>
		<td><?= $this->escapeHtml($item->city) ?></td>
		<td><?= $this->escapeHtml($item->state) ?></td>
		<td><?= $this->escapeHtml($item->zip) ?></td>
		<td><?= $item->web_addr ? $this->escapeHtml($item->web_addr) : 'None' ?>
		</td>
		<td>
			<button onclick="location.href='/simple-address-book/contact/edit/<?= $item->id ?>'">Edit</button>
			<button onclick="location.href='/simple-address-book/contact/delete/<?= $item->id ?>'">Delete</button>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>