<?= $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle('Analytics Code Test')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headLink()->appendStylesheet($this->basePath() . '/css/simple-address-book.css')->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css') ?>
  </head>

  <body>
  	<?php echo $this->content ?>
  </body>
</html>
